<template>
  <BaseHelpModal :is-visible="isVisible" title="Plate Generator - Help" @close="close">
    <div class="help-section">
      <h6 class="help-section-title">What is Plate Generator?</h6>
      <div class="help-content">
        <PlateExampleSvg
          aria-label="Example of plate generated by Plate Generator"
          class="help-image"
        />
        <p>
          The Plate Generator creates switch and stabilizer cutouts for your keyboard layout,
          exporting to SVG and DXF formats for manufacturing processes like laser cutting.
        </p>
        <div class="warning-box">
          <div class="d-flex align-items-center gap-2">
            <BiExclamationTriangle class="text-warning" />
            <div class="small">
              The Plate Generator <strong>does not</strong> prevent usage of settings which are not
              manufacturable in practice.
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="help-section">
      <h6 class="help-section-title">Tabs Overview</h6>
      <div class="help-content">
        <ul class="tips-list">
          <li>
            <strong>Switch Cutouts</strong> - Select switch type (Cherry MX, Alps, Kailh Choc),
            stabilizer style, fillet radius, and kerf compensation.
          </li>
          <li>
            <strong>Holes</strong> - Add corner mounting holes (requires outline) or custom holes at
            arbitrary positions.
          </li>
          <li>
            <strong>Outline</strong> - Choose between no outline, a rectangular border with
            configurable margins and corner radius, or a custom polygon defined by segments.
          </li>
        </ul>
      </div>
    </div>

    <div class="help-section">
      <h6 class="help-section-title">Switch and Stabilizer Settings</h6>
      <div class="help-content">
        <ul class="tips-list">
          <li>
            <strong>Fillet Radius</strong> - Rounds corners of cutouts. Useful for CNC routing where
            sharp internal corners aren't possible. Upper limits of fillet values are dictated by
            geometry, not by actual application constraints.
          </li>
          <li>
            <strong>Size Adjustment (Kerf)</strong> - Kerf is the total width of material removed by
            the cutting tool (e.g. the laser beam). The cutout path shrinks by half the kerf on each
            side so the final physical hole matches the intended size. For example, a 14mm cutout
            with kerf 0.5mm is drawn at 13.5mm; the laser removes 0.25mm per side, resulting in a
            14mm hole. This is an <strong>advanced</strong> option and can often be left at 0.
            Negative values expand cutouts, useful for small adjustments in 3D printing.
          </li>
          <li>
            <strong>Merge Cutouts</strong> - Combines overlapping shapes into single paths. Can be
            useful when stabilizer cutouts overlap with switch cutouts.
          </li>
        </ul>
        In order to adjust orientation of individual switch or stabilizer cutout set
        <code>Switch orientation</code> or <code>Stabilizer orientation</code> property in
        <b>Key Properties</b> panel.
      </div>
    </div>

    <div class="help-section">
      <h6 class="help-section-title">Holes Settings</h6>
      <div class="help-content">
        <ul class="tips-list">
          <li>
            <strong>Corner Mounting Holes</strong> - Option to place holes at each plate corner at a
            specified distance. Requires outline to be set to Rectangle or Custom mode.
          </li>
          <li>
            <strong>Custom Holes</strong> - Positions use keyboard units (U), not millimeters.
            Reference position <em>(0,0)</em> is marked with a red cross.
          </li>
        </ul>
      </div>
    </div>

    <div class="help-section">
      <h6 class="help-section-title">Outline Settings</h6>
      <div class="help-content">
        <ul class="tips-list">
          <li><strong>None</strong> - No outline is generated.</li>
          <li>
            <strong>Rectangle</strong> - A rectangular outline around all cutouts with configurable
            margins and fillet (corner rounding) radius.
          </li>
          <li>
            <strong>Custom</strong> - A closed polygon defined by an explicit list of corner points
            in keyboard units (U). +X right, +Y down relative to the first key center. The shape
            auto-closes (last corner connects back to the first).
          </li>
          <li>
            <strong>Merge with Cutouts</strong> - Place cutouts and outline in a single file,
            otherwise use separate files. Outline file, if separate, has the same <em>(0,0)</em>
            origin point for easier CAD/CAM handling.
          </li>
          <li>
            <strong>Margins</strong> (Rectangle) - Distance from cutout bounds to outline edge. Both
            switch and stabilizer cutouts are considered, but holes are not.
          </li>
          <li><strong>Fillet Radius</strong> (Rectangle) - Rounds corners of the outline.</li>
        </ul>
      </div>
    </div>

    <div class="help-section">
      <h6 class="help-section-title">Credits</h6>
      <div class="help-content">
        <p class="small text-body-secondary">
          Based on
          <a href="https://kbplate.ai03.com/" target="_blank" rel="noopener noreferrer"
            >ai03 Plate Generator</a
          >
          and
          <a href="http://builder.swillkb.com/" target="_blank" rel="noopener noreferrer"
            >swillkb Plate &amp; Case Builder</a
          >.
        </p>
      </div>
    </div>
  </BaseHelpModal>
</template>

<script setup lang="ts">
import BaseHelpModal from './BaseHelpModal.vue'

import BiExclamationTriangle from 'bootstrap-icons/icons/exclamation-triangle.svg'
import PlateExampleSvg from '@/assets/plate-example.svg'

interface Props {
  isVisible: boolean
}

interface Emits {
  (e: 'close'): void
}

defineProps<Props>()
const emit = defineEmits<Emits>()

const close = () => {
  emit('close')
}
</script>

<style scoped>
.warning-box {
  background: var(--bs-tertiary-bg);
  padding: 12px;
  border-radius: 6px;
  border-left: 4px solid var(--bs-warning);
  margin-top: 0.75rem;
  overflow: hidden; /* Prevents overlap with floated images */
}

.help-image {
  float: right;
  max-width: 300px;
  margin-left: 1rem;
  margin-bottom: 0.5rem;
}

@media (max-width: 767.98px) {
  .help-image {
    float: none;
    display: block;
    margin: 0 auto 1rem;
    max-width: 200px;
  }
}
</style>
